//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kazino.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kazino1337Entities4 : DbContext
    {
        public Kazino1337Entities4()
            : base("name=Kazino1337Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank_kazino> bank_kazino { get; set; }
        public virtual DbSet<game> game { get; set; }
        public virtual DbSet<ind_history> ind_history { get; set; }
        public virtual DbSet<rep_game> rep_game { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<trade_chips> trade_chips { get; set; }
        public virtual DbSet<transactions> transactions { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
