//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kazino.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public int id_transact { get; set; }
        public Nullable<int> id_history { get; set; }
        public Nullable<int> transact_sum { get; set; }
        public Nullable<int> id_bank { get; set; }
    
        public virtual bank_kazino bank_kazino { get; set; }
        public virtual ind_history ind_history { get; set; }
    }
}
